[package]
name = "extract-tester"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
markdownify = { path = "../vendor/markdownify" }
unpdf = { path = "../vendor/unpdf", default-features = false, features = ["fast-parse"] }
docx-parser = { path = "../vendor/docx-parser" }
pptx-to-md = { path = "../vendor/pptx-to-md", default-features = false }
base64 = "0.22"
wasm-bindgen = "0.2"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "gif", "bmp", "webp"] }
imageproc = { version = "0.24", default-features = false }
