/**
 * PECP Service — PE Communication Protocol helpers
 *
 * Helper functions for PECP artifact management. The actual PECP content is
 * generated by the agent using the standard document tools (begin → write → finalize).
 *
 * PECP artifacts are:
 * - Auto-approved on finalize (no separate approval flow)
 * - Excluded from artifact lists (is_pecp = true)
 * - Linked to their parent internal document version via parent_version
 *
 * The PECP lifecycle is tied to its parent:
 * - Parent approved → PECP stays as-is
 * - Parent rejected → PECP stays (last known PE communication)
 * - New parent version → new PECP generated, old one superseded by upsertDocument
 */

import { normalizeArtifactKey } from '@/lib/artifacts/utils';
import { INTERNAL_DOCUMENTS } from '@/lib/schema/artifact';

/** Derive the PECP artifact key from the parent document key */
export function pecpKeyForDocument(documentKey: string): string {
    const base = documentKey.replace(/\.md$/, '');
    return normalizeArtifactKey(`${base}-pecp.md`);
}

/** Check if a document type is an internal document that should get a PECP */
export function shouldGeneratePECP(documentType: string): boolean {
    return (INTERNAL_DOCUMENTS as readonly string[]).includes(documentType);
}

/** Check if a given artifact key is a PECP key */
export function isPECPKey(key: string): boolean {
    return normalizeArtifactKey(key).endsWith('-pecp.md');
}
