/**
 * PECP Service — Public Summary of Executive/Internal Documents
 *
 * Helper functions for PECP artifact management. The actual PECP content is
 * generated by the agent using the standard document tools (begin → write → finalize).
 *
 * PECP artifacts are:
 * - Auto-approved on finalize (no separate approval flow)
 * - Hidden from artifact lists (is_hidden = true)
 * - Linked to their parent internal document version via parent_version
 *
 * The PECP lifecycle is tied to its parent:
 * - Parent approved → PECP stays as-is
 * - Parent rejected → PECP is superseded
 * - New parent version → new PECP generated, old one superseded
 */

import type { EntityManager } from '@mikro-orm/core';
import { normalizeArtifactKey } from '@/lib/artifacts/utils';
import { ArtifactVersionEntity } from '@/lib/orm/entities/artifacts/artifact-version.entity';
import { INTERNAL_DOCUMENTS } from '@/lib/schema/artifact';

// ============================================================================
// HELPERS
// ============================================================================

/** Derive the PECP artifact key from the parent document key */
export function pecpKeyForDocument(documentKey: string): string {
    const base = documentKey.replace(/\.md$/, '');
    return normalizeArtifactKey(`${base}-pecp.md`);
}

/** Check if a document type is an internal document that should get a PECP */
export function shouldGeneratePECP(documentType: string): boolean {
    return (INTERNAL_DOCUMENTS as readonly string[]).includes(documentType);
}

/** Check if a given artifact key is a PECP key */
export function isPECPKey(key: string): boolean {
    return normalizeArtifactKey(key).endsWith('-pecp.md');
}

// ============================================================================
// LIFECYCLE — supersede PECP when parent changes
// ============================================================================

/**
 * Supersede all PECP versions linked to a specific parent version.
 * Called when the parent document is rejected or a new version supersedes it.
 */
export async function supersedePECPsForParent(em: EntityManager, parentVersionId: string): Promise<number> {
    const pecpVersions = await em.find(ArtifactVersionEntity, {
        parent_version: parentVersionId,
        status: { $in: ['approved', 'proposed'] },
    });

    for (const v of pecpVersions) {
        v.status = 'superseded';
        v.rejection_reason = 'Parent document version changed';
        v.status_changed_at = new Date();
    }

    if (pecpVersions.length > 0) {
        await em.flush();
    }

    return pecpVersions.length;
}
