export enum WORKERS_LOCAL_ENDPOINTS {
    ChatAction = '/api/chat/handler',
    IntakeAction = '/api/intake/handler',
    AbortAction = '/api/chat/abort',
    SummarizeAction = '/api/chat/summarize',
    ApproveAction = '/api/chat/artifacts/approve',
    RejectAction = '/api/chat/artifacts/reject',
    ImportAction = '/api/chat/artifacts/import',
    UploadAction = '/api/chat/artifacts/upload',
    PresignAction = '/api/chat/artifacts/upload/presign',
    ConfirmAction = '/api/chat/artifacts/upload/confirm',
    DeleteAction = '/api/chat/artifacts/delete',
    ExportAction = '/api/chat/artifacts/export',
    AssociateAction = '/api/chat/artifacts/associate',
    ImagePresignAction = '/api/chat/images/upload/presign',
    ImageConfirmAction = '/api/chat/images/upload/confirm',
    ImageServe = '/api/chat/images',
    ArtifactImageServe = '/api/chat/artifact-image',
    Presets = '/api/chat/presets',
}

export enum WORKERS {
    Chat = 'hi-chat',
    // Services = 'services',
}

export enum CHAT_EP {
    ChatAction = '/chat',
    IntakeAction = '/intake',
    AbortAction = '/abort',
    SummarizeAction = '/summarize',
    ApproveAction = '/artifacts/approve',
    RejectAction = '/artifacts/reject',
    ImportAction = '/artifacts/import',
    UploadAction = '/artifacts/upload',
    PresignAction = '/artifacts/upload/presign',
    ConfirmAction = '/artifacts/upload/confirm',
    DeleteAction = '/artifacts/delete',
    ExportAction = '/artifacts/export',
    AssociateAction = '/artifacts/associate',
    ImagePresignAction = '/images/upload/presign',
    ImageConfirmAction = '/images/upload/confirm',
    ImageServe = '/images',
    ArtifactImageServe = '/artifact-image',
    Presets = '/presets',
}
