/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 4c7bd3f659d5721d60d29d234759f907)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		CLERK_PUBLISHABLE_KEY: string;
		LANGFUSE_HOST: string;
		LANGFUSE_PUBLIC_KEY: string;
		LANGFUSE_ENVIRONMENT: string;
		CORS_ALLOWED_ORIGIN: string;
		WORKER_NAME: string;
		WORKER_NAME_FULL: string;
		ENV: string;
		USER_GATEWAY: DurableObjectNamespace /* UserGateway from hi-objects */;
		CHAT_STREAM_DO: DurableObjectNamespace /* ChatStreamDO from hi-objects */;
		DATABASE_URL: SecretsStoreSecret;
		CLERK_SECRET_KEY: SecretsStoreSecret;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLERK_PUBLISHABLE_KEY" | "LANGFUSE_HOST" | "LANGFUSE_PUBLIC_KEY" | "LANGFUSE_ENVIRONMENT" | "CORS_ALLOWED_ORIGIN" | "WORKER_NAME" | "WORKER_NAME_FULL" | "ENV">> {}
}
