/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime=false --strict-vars=false --env-interface ObjectsEnv` (hash: 1a9325ae2838503c62c0103e8d587f79)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "UserGateway" | "ChatStreamDO" | "GenerationProxyDO";
	}
	interface ObjectsEnv {
		CLERK_PUBLISHABLE_KEY: string;
		LANGFUSE_HOST: string;
		LANGFUSE_PUBLIC_KEY: string;
		LANGFUSE_ENVIRONMENT: string;
		CORS_ALLOWED_ORIGIN: string;
		WORKER_NAME: string;
		WORKER_NAME_FULL: string;
		ENV: string;
		USER_GATEWAY: DurableObjectNamespace<import("./src/index").UserGateway>;
		CHAT_STREAM_DO: DurableObjectNamespace<import("./src/index").ChatStreamDO>;
		GENERATION_PROXY: DurableObjectNamespace<import("./src/index").GenerationProxyDO>;
		DATABASE_URL: SecretsStoreSecret;
		CLERK_SECRET_KEY: SecretsStoreSecret;
		STREAM_AE: AnalyticsEngineDataset;
	}
}
interface ObjectsEnv extends Cloudflare.ObjectsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.ObjectsEnv, "CLERK_PUBLISHABLE_KEY" | "LANGFUSE_HOST" | "LANGFUSE_PUBLIC_KEY" | "LANGFUSE_ENVIRONMENT" | "CORS_ALLOWED_ORIGIN" | "WORKER_NAME" | "WORKER_NAME_FULL" | "ENV">> {}
}
