/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 32e8b879ff54c7c563e793d690978afd)
declare namespace Cloudflare {
    interface GlobalProps {
        mainModule: typeof import('./src/index');
    }
    interface Env {
        CLERK_PUBLISHABLE_KEY: string;
        LANGFUSE_HOST: string;
        LANGFUSE_PUBLIC_KEY: string;
        LANGFUSE_ENVIRONMENT: string;
        ENV: string;
        CORS_ALLOWED_ORIGIN: string;
        DATABASE_URL: SecretsStoreSecret;
        CLERK_SECRET_KEY: SecretsStoreSecret;
        ANTHROPIC_API_KEY: SecretsStoreSecret;
        OPENROUTER_API_KEY: SecretsStoreSecret;
        LANGFUSE_SECRET_KEY: SecretsStoreSecret;
        AUTH_SECRET: SecretsStoreSecret;
    }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
    [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
    interface ProcessEnv
        extends StringifyValues<
            Pick<
                Cloudflare.Env,
                | 'CLERK_PUBLISHABLE_KEY'
                | 'LANGFUSE_HOST'
                | 'LANGFUSE_PUBLIC_KEY'
                | 'LANGFUSE_ENVIRONMENT'
                | 'ENV'
                | 'CORS_ALLOWED_ORIGIN'
            >
        > {}
}
