/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6d65c9c5d88da49bdd94b8388859a68a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		CLERK_PUBLISHABLE_KEY: "pk_test_YnJpZ2h0LWhhcmUtMTkuY2xlcmsuYWNjb3VudHMuZGV2JA";
		LANGFUSE_HOST: "https://us.cloud.langfuse.com";
		LANGFUSE_PUBLIC_KEY: "pk-lf-82870529-7f46-4e5e-9195-ada413019895";
		LANGFUSE_ENVIRONMENT: "production" | "dev";
		ENV: "dev";
		CORS_ALLOWED_ORIGIN: "https://dev-app.hyperfund.ai";
		DATABASE_URL: SecretsStoreSecret;
		CLERK_SECRET_KEY: SecretsStoreSecret;
		ANTHROPIC_API_KEY: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
		LANGFUSE_SECRET_KEY: SecretsStoreSecret;
		AUTH_SECRET: SecretsStoreSecret;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLERK_PUBLISHABLE_KEY" | "LANGFUSE_HOST" | "LANGFUSE_PUBLIC_KEY" | "LANGFUSE_ENVIRONMENT" | "ENV" | "CORS_ALLOWED_ORIGIN">> {}
}
