/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 30b5bd9f29f14ed043941444cddd60b8)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		CLERK_PUBLISHABLE_KEY: string;
		LANGFUSE_HOST: string;
		LANGFUSE_PUBLIC_KEY: string;
		LANGFUSE_ENVIRONMENT: string;
		CORS_ALLOWED_ORIGIN: string;
		CHAT_OUTPUT_SAFETY_ENABLED: string;
		WORKER_NAME: string;
		WORKER_NAME_FULL: string;
		ENV: string;
		USER_GATEWAY: DurableObjectNamespace<import('../objects/src/index').UserGateway>;
		CHAT_STREAM_DO: DurableObjectNamespace<import('../objects/src/index').ChatStreamDO>;
		GENERATION_PROXY: DurableObjectNamespace<import('../objects/src/index').GenerationProxyDO>;
		ARTIFACTS_BUCKET: R2Bucket;
		DATABASE_URL: SecretsStoreSecret;
		CLERK_SECRET_KEY: SecretsStoreSecret;
		ANTHROPIC_API_KEY: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
		OPENAI_KEY: SecretsStoreSecret;
		LANGFUSE_SECRET_KEY: SecretsStoreSecret;
		AUTH_SECRET: SecretsStoreSecret;
		FIRECRAWL_API_KEY: SecretsStoreSecret;
		R2_ACCESS_KEY_ID: SecretsStoreSecret;
		R2_SECRET_ACCESS_KEY: SecretsStoreSecret;
		CF_ACCOUNT_ID: SecretsStoreSecret;
		EMBEDDING_QUEUE: Queue;
		EXTRACTION_QUEUE: Queue;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLERK_PUBLISHABLE_KEY" | "LANGFUSE_HOST" | "LANGFUSE_PUBLIC_KEY" | "LANGFUSE_ENVIRONMENT" | "CORS_ALLOWED_ORIGIN" | "CHAT_OUTPUT_SAFETY_ENABLED" | "WORKER_NAME" | "WORKER_NAME_FULL" | "ENV">> {}
}
