/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 83135e8b0d11f3c2f8ad1a708512dc00)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		CLERK_PUBLISHABLE_KEY: string;
		LANGFUSE_HOST: string;
		LANGFUSE_PUBLIC_KEY: string;
		LANGFUSE_ENVIRONMENT: string;
		CORS_ALLOWED_ORIGIN: string;
		WORKER_NAME: string;
		WORKER_NAME_FULL: string;
		ENV: string;
		ARTIFACTS_BUCKET: R2Bucket;
		DATABASE_URL: SecretsStoreSecret;
		AUTH_SECRET: SecretsStoreSecret;
		OPENAI_KEY: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
		LANGFUSE_SECRET_KEY: SecretsStoreSecret;
		R2_ACCESS_KEY_ID: SecretsStoreSecret;
		R2_SECRET_ACCESS_KEY: SecretsStoreSecret;
		CF_ACCOUNT_ID: SecretsStoreSecret;
		EXTRACT_RUST: Fetcher /* extract-rust */;
		EMBEDDING_QUEUE: Queue;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLERK_PUBLISHABLE_KEY" | "LANGFUSE_HOST" | "LANGFUSE_PUBLIC_KEY" | "LANGFUSE_ENVIRONMENT" | "CORS_ALLOWED_ORIGIN" | "WORKER_NAME" | "WORKER_NAME_FULL" | "ENV">> {}
}
