/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime=false --strict-vars=false --env-interface ExtractionEnv` (hash: 62761e9db19a9cdcc8a5b45639552da9)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ExtractionEnv {
		CLERK_PUBLISHABLE_KEY: string;
		LANGFUSE_HOST: string;
		LANGFUSE_PUBLIC_KEY: string;
		LANGFUSE_ENVIRONMENT: string;
		CORS_ALLOWED_ORIGIN: string;
		WORKER_NAME: string;
		WORKER_NAME_FULL: string;
		ENV: string;
		ARTIFACTS_BUCKET: R2Bucket;
		DATABASE_URL: SecretsStoreSecret;
		AUTH_SECRET: SecretsStoreSecret;
		OPENAI_KEY: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
		LANGFUSE_SECRET_KEY: SecretsStoreSecret;
		R2_ACCESS_KEY_ID: SecretsStoreSecret;
		R2_SECRET_ACCESS_KEY: SecretsStoreSecret;
		CF_ACCOUNT_ID: SecretsStoreSecret;
		REDUCTO_API_KEY: SecretsStoreSecret;
		EXTRACT_RUST: Fetcher /* hi-extract-rust */;
		EMBEDDING_QUEUE: Queue;
	}
}
interface ExtractionEnv extends Cloudflare.ExtractionEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.ExtractionEnv, "CLERK_PUBLISHABLE_KEY" | "LANGFUSE_HOST" | "LANGFUSE_PUBLIC_KEY" | "LANGFUSE_ENVIRONMENT" | "CORS_ALLOWED_ORIGIN" | "WORKER_NAME" | "WORKER_NAME_FULL" | "ENV">> {}
}
