/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime=false --strict-vars=false --env-interface EmbeddingEnv` (hash: ca8cc1275535c381b3420271d65e66e4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface EmbeddingEnv {
		CLERK_PUBLISHABLE_KEY: string;
		LANGFUSE_HOST: string;
		LANGFUSE_PUBLIC_KEY: string;
		LANGFUSE_ENVIRONMENT: string;
		CORS_ALLOWED_ORIGIN: string;
		WORKER_NAME: string;
		WORKER_NAME_FULL: string;
		ENV: string;
		DATABASE_URL: SecretsStoreSecret;
		OPENAI_KEY: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
		LANGFUSE_SECRET_KEY: SecretsStoreSecret;
		AUTH_SECRET: SecretsStoreSecret;
		PREVIEW_DB_MAP: KVNamespace;
	}
}
interface EmbeddingEnv extends Cloudflare.EmbeddingEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.EmbeddingEnv, "CLERK_PUBLISHABLE_KEY" | "LANGFUSE_HOST" | "LANGFUSE_PUBLIC_KEY" | "LANGFUSE_ENVIRONMENT" | "CORS_ALLOWED_ORIGIN" | "WORKER_NAME" | "WORKER_NAME_FULL" | "ENV">> {}
}
