/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime=false --strict-vars=false --env-interface StreamStateEnv` (hash: 3bd28c31f05d6140217ee2f6c885c9a0)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ChatStreamStateDO";
	}
	interface StreamStateEnv {
		CLERK_PUBLISHABLE_KEY: string;
		LANGFUSE_HOST: string;
		LANGFUSE_PUBLIC_KEY: string;
		LANGFUSE_ENVIRONMENT: string;
		CORS_ALLOWED_ORIGIN: string;
		WORKER_NAME: string;
		WORKER_NAME_FULL: string;
		ENV: string;
		CHAT_STREAM_STATE_DO: DurableObjectNamespace<import("./src/index").ChatStreamStateDO>;
		STREAM_AE: AnalyticsEngineDataset;
		PREVIEW_DB_MAP: KVNamespace;
	}
}
interface StreamStateEnv extends Cloudflare.StreamStateEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.StreamStateEnv, "CLERK_PUBLISHABLE_KEY" | "LANGFUSE_HOST" | "LANGFUSE_PUBLIC_KEY" | "LANGFUSE_ENVIRONMENT" | "CORS_ALLOWED_ORIGIN" | "WORKER_NAME" | "WORKER_NAME_FULL" | "ENV">> {}
}
